services:
  postegres:
    image: postgres:17.4-alpine
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5432:5432"
    volumes:
      - pg-jobsmint:/var/lib/postgresql/data

  redis-cache:
    image: redis:latest
    ports:
      - "6379:6379"
    volumes:
      - redis-jobsmint:/data
volumes:
  redis-jobsmint:
  pg-jobsmint:
